from . import training
from . import training_date
from . import training_module
from . import training_participant
from . import training_qualification
from . import training_qualification_type
from . import training_qualification_category
from . import training_medical_fitness_level
from . import res_partner
