from . import asset_type
from . import asset
from . import business_risk_type
from . import business_risk
from . import damage
from . import department
from . import extent_of_damage
from . import probability
from . import residual_risk
from . import risk_zone
from . import res_partner
from . import risk_assessment
